# Generated by Django 3.0.8 on 2022-05-16 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0003_auto_20220504_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'група', 'verbose_name_plural': 'Довідка груп'},
        ),
        migrations.AlterModelOptions(
            name='groupstudent',
            options={'verbose_name': 'Група студнтів', 'verbose_name_plural': 'Групи студентів'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'дисципліна', 'verbose_name_plural': 'Довідка дисципін'},
        ),
        migrations.AlterModelOptions(
            name='ratingitemstatus',
            options={'verbose_name': 'статус оцінки', 'verbose_name_plural': 'Довідка статусів оцінок'},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'verbose_name': 'запис журналу', 'verbose_name_plural': 'Оцінки'},
        ),
        migrations.AlterField(
            model_name='grade',
            name='lessons',
            field=models.ManyToManyField(related_name='grade', to='journal.Lesson', verbose_name='Дисципліни групи'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='number',
            field=models.SmallIntegerField(verbose_name='Число'),
        ),
        migrations.AlterField(
            model_name='groupstudent',
            name='create_group',
            field=models.DateField(verbose_name='Дата створення групи'),
        ),
        migrations.AlterField(
            model_name='groupstudent',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='groupstudent',
            name='grade',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='journal.Grade', verbose_name='Назва групи'),
        ),
        migrations.AlterField(
            model_name='groupstudent',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='Дата оновлення'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='ratingitemstatus',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Статус оцінки'),
        ),
        migrations.AlterField(
            model_name='score',
            name='created',
            field=models.DateField(verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='score',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.GroupStudent', verbose_name='Назва групи'),
        ),
        migrations.AlterField(
            model_name='score',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Lesson', verbose_name='Дисципліна'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.SmallIntegerField(choices=[(5, '5'), (4, '4'), (3, '3'), (2, '2')], verbose_name='Оцінка'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.RatingItemStatus', verbose_name='Статус оцінки'),
        ),
        migrations.AlterField(
            model_name='score',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'user_status': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_teacher', to=settings.AUTH_USER_MODEL, verbose_name='Викладач'),
        ),
        migrations.AlterField(
            model_name='score',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата оновлення'),
        ),
    ]
