# Generated by Django 3.0.8 on 2022-05-16 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'verbose_name': 'Розсилка', 'verbose_name_plural': 'Розсилки'},
        ),
        migrations.AlterField(
            model_name='mailing',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_from', to=settings.AUTH_USER_MODEL, verbose_name='Відправник'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='message',
            field=models.TextField(verbose_name='Текст повідомлення'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Назва розсилки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='to_users',
            field=models.ManyToManyField(related_name='mailing_to', to=settings.AUTH_USER_MODEL, verbose_name='Отримувачі'),
        ),
    ]
