# Generated by Django 3.0.8 on 2022-05-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='study_form',
            field=models.CharField(choices=[('Бюджет', 'Бюджет'), ('Контракт', 'Контракт')], default=0, max_length=20, verbose_name='Форма навчання'),
            preserve_default=False,
        ),
    ]
