# Generated by Django 3.0.8 on 2022-05-16 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20220516_1608'),
        ('people', '0002_user_study_form'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакти'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студенти'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Викладач', 'verbose_name_plural': 'Викладачі'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Користувач', 'verbose_name_plural': 'Користувачі'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='study_form',
        ),
        migrations.AddField(
            model_name='student',
            name='study_form',
            field=models.CharField(choices=[('Бюджет', 'Бюджет'), ('Контракт', 'Контракт'), ('Немає', 'Немає')], default=0, max_length=20, verbose_name='Форма навчання'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='journal.GroupStudent', verbose_name='Навчається в групі'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='group_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to='journal.GroupStudent'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='lessons',
            field=models.ManyToManyField(related_name='teachers', to='journal.Lesson', verbose_name='Викладає дисципліни'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.CharField(max_length=99, verbose_name='Посада'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата народження'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(max_length=130, verbose_name='По-батькові'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('М', 'М'), ('Ж', 'Ж')], max_length=1, verbose_name='Стать'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='Дата оновлення'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_status',
            field=models.CharField(choices=[('teacher', 'Учитель'), ('student', 'Студент')], max_length=15, verbose_name='Статус користувача'),
        ),
    ]
