# Generated by Django 3.0.8 on 2022-05-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20220516_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_status',
            field=models.CharField(choices=[('teacher', 'Викладач'), ('student', 'Студент')], max_length=15, verbose_name='Статус користувача'),
        ),
    ]
