# Generated by Django 3.0.8 on 2022-05-18 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_student_course_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course_supervisor',
            field=models.ForeignKey(limit_choices_to={'user_status': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor', to=settings.AUTH_USER_MODEL, verbose_name='Викладач'),
        ),
        migrations.AlterField(
            model_name='student',
            name='entry_year',
            field=models.IntegerField(verbose_name='Рік вступу'),
        ),
    ]
