# Generated by Django 3.0.8 on 2022-05-18 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20220518_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_supervisor',
            field=models.ForeignKey(limit_choices_to={'user_status': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor', to='people.Teacher', verbose_name='Викладач'),
        ),
    ]
