# Generated by Django 3.0.8 on 2022-05-19 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_auto_20220518_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='diploma_supervisor',
            field=models.ForeignKey(limit_choices_to={'user_status': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisors', to=settings.AUTH_USER_MODEL, verbose_name='Викладач'),
        ),
        migrations.AddField(
            model_name='student',
            name='diploma_work',
            field=models.CharField(default=1, max_length=100, verbose_name='Тема курсової роботи'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='course_supervisor',
            field=models.ForeignKey(limit_choices_to={'user_status': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor', to=settings.AUTH_USER_MODEL, verbose_name='Викладач'),
        ),
    ]
