# Generated by Django 3.0.8 on 2022-05-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_auto_20220519_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='group_manager',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=130, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=130, verbose_name='Фамілія'),
        ),
    ]
