# Generated by Django 3.0.8 on 2022-05-21 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20220516_1608'),
        ('people', '0011_auto_20220521_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='group_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to='journal.GroupStudent'),
        ),
    ]
